### ISSUE TITLE
Syntax error with simple table

### ISSUE THREAD

**Issue by matthewjumpsoffbuildings** [colopl/laravel-spanner#136] opened 2023-09-20 15:55 UTC
I am trying to create a simple table with a single column ('id'), like so

```php
Schema::create('test', function (Blueprint $table) {
	$table->uuid('id');
	$table->primary('id');
});
```

When I run this (just testing it in a console command for now), I get the following error:
```
   Google\Cloud\Core\Exception\BadRequestException 

  {
    "message": "[ERROR] syntax error at or near \"`\"; failed to parse the DDL statements.",
    "code": 3,
    "status": "INVALID_ARGUMENT",
    "details": []
}

  at vendor/google/cloud-core/src/GrpcRequestWrapper.php:263
```

No idea why, its not exactly very helpful

**Comment by matthewjumpsoffbuildings** [comment] 2023-09-20 18:11
Turns out this is because my Spanner instance was in PostgreSQL mode... The docs should really make it clearer that this library only works if the instance is in Google SQL mode.

Is there a different way to use Spanner in PostgreSQL mode with the standard PostgreSQL laravel driver?

**Comment by taka-oyama** [comment] 2023-09-21 00:25
Why not just use the PostgreSQL laravel driver?

**Comment by taka-oyama** [comment] 2023-09-21 00:26
> The docs should really make it clearer that this library only works if the instance is in Google SQL mode.

We would really appreciate a PR!

**Comment by matthewjumpsoffbuildings** [comment] 2023-09-21 01:29
> Why not just use the PostgreSQL laravel driver?

Is this even possible? I cant seem to work out how to connect to Spanner in this way?

**Comment by taka-oyama** [comment] 2023-09-21 01:33
Have you tried the [pgadapter](https://cloud.google.com/spanner/docs/pgadapter)?

**Comment by matthewjumpsoffbuildings** [comment] 2023-09-21 02:36
No, I will look into that thanks.

Is there some kind of limitation with the Spanner php library that means it only works if its not in PostgreSQL mode? Wouldnt it be better and more flexible if you could use either Google SQL or PostgreSQL?

**Comment by taka-oyama** [comment] 2023-09-21 02:44
It would be better, but when we created the driver, PgSQL mode did not exist.

I don't think we (Colopl Inc) wants to spend resources on supporting something we don't use unless there is a strong reason for using it.

**Comment by matthewjumpsoffbuildings** [comment] 2023-09-21 02:46
Oh right it's not that it's not possible, it would just require additional changes to this codebase?

How much work do you think it would be to add it? I am considering options here and may be interested in trying to add PostgreSQL support to this library

**Comment by matthewjumpsoffbuildings** [comment] 2023-09-21 02:55
> > The docs should really make it clearer that this library only works if the instance is in Google SQL mode.
> 
> We would really appreciate a PR!

Here's a PR https://github.com/colopl/laravel-spanner/pull/137

**Comment by taka-oyama** [comment] 2023-09-21 03:07
Thank you for the PR.

> How much work do you think it would be to add it?

I assume it would be a hefty task. I think you can start by swapping the Query/Schema builder with the Posgtres one and make it kinda work. But to make it production ready you have to write tests and add some spanner specific features like interleaving. 

With all that said, I'm not sure adding postgres mode makes much sense because laravel's database driver is already an abstraction layer which exists so that you don't have to worry much about the minor differences in the underlying SQL.

**Comment by matthewjumpsoffbuildings** [comment] 2023-09-21 03:21
> With all that said, I'm not sure adding postgres mode makes much sense because laravel's database driver is already an abstraction layer which exists so that you don't have to worry much about the minor differences in the underlying SQL.

True, but having the database in PostgreSQL mode improves portability and flexibility, for example I think if you want to use the PGAdapter it has to be in PostgreSQL mode

I can certainly see scenarios where being locked in to GoogleSQL mode would be a limitation or issue. Having both options is much more ideal

**Comment by taka-oyama** [comment] 2023-09-21 03:43
> if you want to use the PGAdapter it has to be in PostgreSQL mode

But that would only be an issue if there was a feature you want to use that is only included in PostgreSQL mode which I'm not sure exists?

> I can certainly see scenarios where being locked in to GoogleSQL mode would be a limitation or issue.

Can you provide some examples? 

We've moved some data from Spanner to TiDB in the past and we didn't have much trouble with it.

**Comment by taka-oyama** [comment] 2023-09-21 03:51
PostgresSQL mode makes sense to me if you are migrating code from PostgresSQL to Cloud Spanner and don't have any abstraction layer underneath.

**Comment by matthewjumpsoffbuildings** [comment] 2023-09-21 04:30
Oh I dont have any particular use case in mind, its more just a general thing that for maximum flexibility both options should be supported. Also ideally an adapter library like this would have maximum coverage of Spanners feature set

For example I can imagine a situation where you might want a different tool to connect to the data, separate to laravel, via the PGAdapter

**Comment by taka-oyama** [comment] 2023-10-06 05:25
Closing since the question related to the issue is answered.

**Closed by taka-oyama** 2023-10-06 05:25 UTC
Labels: question
